"use client";

import { useState } from "react";
import { useTitle } from "@/src/hooks/useTitle";
import { OwnershipTimeline } from "./OwnershipTimeline";
import { TitleTransferModal } from "./TitleTransferModal";
import { titleStatus, type LandTitle } from "./titleTypes";

const money = new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 });

export function TitleDetail({ parcel }: { parcel: LandTitle | null }) {
  const { title, isLoading, error, gatewayUrl } = useTitle(parcel); const [transferOpen, setTransferOpen] = useState(false);
  if (!title) return <aside className="flex min-h-[440px] items-center justify-center rounded-2xl border border-dashed border-zinc-300 bg-white p-8 text-center text-sm text-zinc-500">Select a highlighted parcel to inspect its verified title.</aside>;
  const facts = [["Parcel ID", title.parcelId], ["Location", title.location], ["Area", `${title.areaHectares} hectares`], ["Crop", title.cropType], ["Soil", title.soilClassification], ["Market value", money.format(title.marketValue)]];
  return <><aside className="rounded-2xl border border-zinc-200 bg-white p-6 shadow-sm"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-emerald-700">ERC-721 title #{title.tokenId}</p><h2 className="mt-2 text-xl font-bold text-zinc-900">{title.name}</h2><p className="mt-1 font-mono text-xs text-zinc-500">Owner {title.owner}</p></div><span className="rounded-full px-3 py-1 text-xs font-semibold" style={{ backgroundColor: `${titleStatus[title.status].color}1a`, color: titleStatus[title.status].color }}>{titleStatus[title.status].label}</span></div><div className="mt-5 grid grid-cols-2 gap-x-5 gap-y-4 border-y border-zinc-100 py-5">{facts.map(([label, value]) => <div key={label}><dt className="text-xs text-zinc-500">{label}</dt><dd className="mt-1 text-sm font-semibold text-zinc-800">{value}</dd></div>)}</div><div className="mt-5 flex items-center justify-between"><div><p className="text-sm font-semibold text-zinc-900">On-chain verification</p><p className="text-xs text-zinc-500">Owner matches the connected title registry.</p></div><span className="text-sm font-bold text-emerald-700">✓ Verified</span></div>{isLoading && <p className="mt-3 text-xs text-zinc-500">Loading IPFS metadata…</p>}{error && <p className="mt-3 text-xs text-amber-700">{error}</p>}<button onClick={() => setTransferOpen(true)} className="mt-5 w-full rounded-lg bg-emerald-700 px-4 py-3 text-sm font-bold text-white hover:bg-emerald-800">Send title</button><section className="mt-7"><h3 className="text-sm font-bold text-zinc-900">Documents</h3><div className="mt-3 space-y-2">{title.documents.map((document) => <a key={document.id} href={gatewayUrl(document.uri)} target="_blank" rel="noreferrer" className="flex items-center justify-between rounded-lg bg-zinc-50 px-3 py-2.5 text-sm text-zinc-700 hover:bg-emerald-50"><span>{document.type === "pdf" ? "PDF" : "DOC"} · {document.label}</span><span className="text-emerald-700">Open ↗</span></a>)}</div></section><section className="mt-7"><h3 className="mb-4 text-sm font-bold text-zinc-900">Ownership history</h3><OwnershipTimeline history={title.history} /></section></aside>{transferOpen && <TitleTransferModal tokenId={title.tokenId} owner={title.owner} onClose={() => setTransferOpen(false)} />}</>;
}
